name: Debug Secrets

on: [workflow_dispatch] # Allows manual trigger

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo masked secret
        run: echo "MY_SECRET=${{ secrets.PRODUCT_ENV_SECRETS }}"

      - name: Echo unmasked secret (use with caution)
        run: |
          echo "::add-mask::${{ secrets.PRODUCT_ENV_SECRETS }}" # Masks it in later steps
          echo "MY_SECRET=$(echo ${{ secrets.PRODUCT_ENV_SECRETS }})"
